Nombre de la bdd: GestionDeGastosTP

CREATE TABLE Usuario
(
Id INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Nombre NVARCHAR(25) NOT NULL,
Correo NVARCHAR(50) NOT NULL,
Password NVARCHAR(100) NOT NULL,
Fondo DECIMAL (12,2) NOT NULL,
)

CREATE TABLE Etiqueta
(
Id INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Nombre NVARCHAR (15) NOT NULL,
Descripcion NVARCHAR(100),
IdUsuario INT NOT NULL REFERENCES Usuario(Id) 
GastoEtiqueta DECIMAL (12,2) NOT NULL,
)

CREATE TABLE Consumo
(
Id INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
Monto DECIMAL (12,2) NOT NULL,
IdEtiqueta INT NOT NULL REFERENCES Etiqueta(Id),
Fecha DATETIME NOT NULL,
IdUsuario INT NOT NULL REFERENCES Usuario(Id),
Descripcion NVARCHAR(100)
)




